### ISSUE TITLE
16:9 widescreen support

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#385]
Make the game run in 16:9 widescreen mode without stretching the pixels.  One of the possible solutions is to increase the player's view field in x and y directions.

`rigel::renderer::determineDefaultViewport()` determines the viewport size of the game. However, changing it to the display size stretches the pixels. There should be another approach where viewing field of camera gets increased for supporting widescreen.    

If you can point me to some of the changes needed, I can do this work.

**Comment by lethal-guitar** [comment]
That's a nice idea! Sure thing, I'll add more information later.

**Comment by lethal-guitar** [comment]
Ok, so I think the major steps are:

1. Do #387 (I'll add more information to that as well). This will make it possible to use the whole screen when drawing the game.
2. Change the code [here](https://github.com/lethal-guitar/RigelEngine/blob/8dbade620b2de2cfd6a33fd5d406e502d2268276/src/game_logic/game_world.cpp#L409) to take the "wide-screen enabled" option into account, and set up a wider clip rect and adjusted translation accordingly
3. Change `MapRenderer` so it's possible to specify how many tiles to draw along x and y when calling `renderBackground`/`renderForeground`
4. Change `RenderingSystem::update` to take the "wide-screen enabled" option into account, and draw the map accordingly. 

That should be it for the most part. I'll try to add some more detailed info sometime over the next days.

**Comment by lethal-guitar** [comment]
@pratikone ok, I've added more information to #387. Would this be enough to get started? Let me know if you have questions or would like more info!

**Comment by pratikone** [comment]
Thanks for the writeup. It was good enough to get me started.  
Now, I am stuck at a different place. I modified some code here and there to see what causes the viewport to change ([ugly hacky code](https://github.com/pratikone/RigelEngine/commit/eabe6379b877952e7374e03a9feac02687e51c7e)).  Now, changing GameTraits::viewPortWidthPx from 320 to anything greater causes some serious crashes during reading textures and other stuff. How to take care of that ? The [ugly hacky code](https://github.com/pratikone/RigelEngine/commit/eabe6379b877952e7374e03a9feac02687e51c7e) does the workaround of storing this 320 value in a different variable and use it at the crashing places.

**Comment by lethal-guitar** [comment]
Hey @pratikone, ok cool!

I guess changing these constants could be a bit tricky - they are intended to represent properties of the original implementation, so a lot of code is going to assume they will have certain values. I guess it could still make sense to introduce separate constants for the texture loading, since it's kind of a coincidence that the textures have the same size as the original screen resolution, now that I think about it.. Maybe adding a new constant `fullScreenImageWidth`/`Height`? Basically like what you did in your hack, just with different names.

To play around with changing the view port, you could also change the code [here](https://github.com/lethal-guitar/RigelEngine/blob/8dbade620b2de2cfd6a33fd5d406e502d2268276/src/game_logic/game_world.cpp#L409) to use the numbers you'd like, and leave the constants unchanged. Then you'll have to change `MapRenderer` as well, but I guess you'll want to do that at some point anyway, once you want to make the widescreen rendering configurable at runtime.

Ah yes, the backdrop - I forgot about that, you'll need to adapt [the code](https://github.com/lethal-guitar/RigelEngine/blob/8dbade620b2de2cfd6a33fd5d406e502d2268276/src/engine/map_renderer.cpp#L86) as well as part of your changes. At the moment, the backdrop is rendered as just one 320x200 texture, which is drawn 2 to 3 times additionally to implement scrolling.

A much nicer solution would be to render the backdrop to fill the entire screen, and then use `GL_REPEAT` on the texture to make it repeat automatically. That would also solve the issue you're seeing on your branch. Unfortunately, this won't work for OpenGL ES, which doesn't allow using `GL_REPEAT` on non-power of two textures, so it would need to be emulated in a shader for the GL ES version. But maybe you can still do the `GL_REPEAT` on your branch to move forward, I'm happy to fix it for GL ES once you're ready to merge something. Does that sound good? Let me know if you need more info!

**Comment by pratikone** [comment]
Your suggestions helped tremendously. I followed your advice to have different set of dimensions for different things. You can check the code [here 👍](https://github.com/lethal-guitar/RigelEngine/compare/master...pratikone:widescreen) 
I shifted the hud to the side and then changed dimensions so that MapRenderer render foreground for that new part and entity system recognise it as Far right corner for game mechanics. You can see the [screenshot](https://imgur.com/gallery/dzcJcII) here as the illustration of the new changes. I have touched the backdrop yet as it will require some more effort.      
Current issue : cannot expand the viewport. I have tried modifying clipRect area, modifying glViewport calls as well as glScissors call, but I cannot widen the viewport so that the hud stops clipping. Every effort streches the pixels rather than widening the viewport. What do you suggest to widen the viewport to prevent the hud from clipping ?

**Comment by lethal-guitar** [comment]
> Current issue : cannot expand the viewport. I have tried modifying clipRect area, modifying glViewport calls as well as glScissors call and framebuffersize, but I cannot widen the viewport so that the hud stops clipping. Every effort streches the pixels rather than widening the viewport.

There is a top-level render target [here](https://github.com/lethal-guitar/RigelEngine/blob/c5ebb5502c281dfe59c7b4b80e2ce523730f2092/src/game_main.cpp#L79), which you would have to adapt in size as well - maybe that's the issue?

I admit it's a bit confusing at the moment with the way things are set up, but essentially, everything is rendered into this one render target, which is then stretched [on this line](https://github.com/lethal-guitar/RigelEngine/blob/c5ebb5502c281dfe59c7b4b80e2ce523730f2092/src/game_main.cpp#L196) according to whatever the "logical display size" in the `Renderer` is.

The effect is that all in-game content is rendered into a 320x200 buffer, which is then rendered with a projection matrix and view port to simulate being rendered onto a _virtual_ 320x240 screen centered in the middle - this causes the 320x200 image to be both upscaled to whatever the native resolution is, as well as being corrected into a 4:3 aspect ratio (as would happen on a CRT monitor back in the day).

With https://github.com/lethal-guitar/RigelEngine/issues/387, this would change so that it's easy to setup a different viewport and matrix and be able to use the full screen. I'll see if I can do some of these changes later today, that should make things easier for you!

**Comment by pratikone** [comment]
@lethal-guitar thanks for your entire help. I have pushed my PR for widescreen. It was a fun + frustrating experience to figure everything out and your suggestions and code changes helped a lot. I always wanted to work on an open-sourced game engine for a game which I have played and enjoyed. Rigel Engine filled that need.
