### ISSUE TITLE
High-DPI support

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#392]
This is needed to make text drawn via ImGui look good on Retina displays (OS X) or with UI scaling enabled (Windows).

Needs #401

**Comment by tmilker** [comment]
Would this include supporting 4k?  It seems the engine just runs 2x 1080p pixel size on a 4k display, so I can't seem to get the cool expanded game width that ultrawide displays have.

**Comment by lethal-guitar** [comment]
@tmilker What aspect ratio does your display have? Did you enable the wide-screen mode in the options menu? 4k should already work, at least it does on my 16:9 4k screen under Windows.

The High-DPI support mentioned in this issue is mainly about making text look crisper on Mac Retina displays.

**Comment by tmilker** [comment]
3840x2160 @ 100% scale in Windows 10.  In full screen, it appears as if it's scaling 1920x1080 up by 2 instead of rendering at 3840x2160.  I can't control the windowed resolution(can't even move the window) but it's only 1920x1080 too(takes up 1/4 of the screen in the upper left).  I thought I'd get the same size pixels but twice as many of them in 4K but that doesn't seem to be what's happening.

**Comment by lethal-guitar** [comment]
> I thought I'd get the same size pixels but twice as many of them in 4K but that doesn't seem to be what's happening.

Ah no, that's not what it's doing, it always scales up proportionally to whatever screen resolution you have. You can however enable wide-screen mode by going into the options menu and then "enhancements", and this way you will see more of the game world to the left and right.

In the near-ish future, I'm going to release an update that adds support for high resolution mods, so if someone makes 4k-compatible versions of the game graphics these would then take advantage of all the pixels in a 4k screen.

**Comment by tmilker** [comment]
Yeah, I've enabled widescreen.  I guess because I saw it was supporting ultrawide, it would support 4K but if you're only rendering the game world further to the left and right and not up and down, it would be limited to only ultrawide aspect ratios for extreme left-right visibility.  This would be possible on 16:9 with black bars but I guess you didn't write your engine that way.  Thanks for the info.

**Comment by lethal-guitar** [comment]
Regarding:

> I can't control the windowed resolution(can't even move the window)

Yeah I think there's a bug currently which makes the window appear in a position where the title bar is off screen - I'm going to look into fixing it. You can try pressing Windows Key + Left Arrow to snap the window to the left edge of the screen, and that should make it resizable then. Or you can edit the config file to set a window size, see https://github.com/lethal-guitar/RigelEngine/wiki/FAQ#where-are-saved-games-settings-etc-stored

**Comment by tmilker** [comment]
That worked perfect.  Set the window location to 520, 0 and width to 3840 and now I get the nice ultrawide game world. Thanks!

**Comment by lethal-guitar** [comment]
Sweet! 👍🏻
