### ISSUE TITLE
Make new options menu thematically similar to existing Duke Nukem  2 menus

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#404]
The new options menu is pretty good step towards richer experience. It opens plenty of scenarios where new options menu can be used. However, it is jarring to use right now because how different it looks and feels compared to rest of the menus in Duke Nukem II. The game uses keyboard for menu navigation but options menu abruptly requires mouse. It also looks not consistent with rest of the ui of the game (it is too clean and refined, less pixel art).

**Comment by lethal-guitar** [comment]
Yeah keyboard support (as well as gamepad support!) is definitely missing in the options menu right now. I'm planning to add it very soon!

Regarding the look/style, I'm a bit torn personally. On one hand, I can see that it would be nice to stay true to the original look & feel. On the other hand, there are some reasons why I chose to do it this way:

* Using off-the-shelf ImGui widgets makes UI development very fast and effortless. This means we can very quickly extend and iterate on the options menu.
* It also means we can have widgets that have no equivalent in the original Duke 2 menus, like the sliders for volume. I'm sure it's possible to create convincing, good looking widgets out of the original art assets, or even design something new that fits in well with the art style, but this kind of art/design work is not something I'm good at.
* In the end, the options available for RigelEngine will be quite different from what's available in the original Duke 2, e.g. featuring various enhancements (like widescreen mode). I personally don't mind the difference in look and feel, because most of the options will result in deviating somewhat from a fully authentic experience when enabled - so the menu being different reminds me that I'm entering new territory, in a way.

That being said, I'm totally open to RigelEngine having a more true to the original options menu! It's just not something that I see myself having the expertise/skills to implement, and I feel like it might make more sense to implement this new options menu style once the available options have developed a bit, and it's clearer what options we will have, what kinds of widgets we need etc.

And contributions/suggestions are always welcome of course!

**Comment by pratikone** [comment]
I am on board with you on this one. Let's flesh it out more and then we can look for skinning/theming it appropriately within the game world. I see the importance of denoting to the user what is different from vanilla experience which we can do with a better theming after the above-mentioned reasons have been completed.

**Comment by lethal-guitar** [comment]
I have been thinking about this one again recently in the context of gamepad support. The original Duke Nukem II menu style lends itself much better to gamepad navigation compared to the current options menu.

I want to first implement a mechanism to make it easy to implement original-style menus without having to use DukeScript. But once we have that, I'm thinking that we could have most of the options available as "classic" menu, and then we could potentially have a "Advanced Settings" point which would bring up the current options menu for more complex options, if necessary.

For example, we could have on/off toggles for sound/music, but the volume sliders would maybe be in the "Advanced" section. Sounds like a good compromise to me, which would allow us to use the existing graphics where possible, and defer to ImGui for more complex widgets like sliders.

**Comment by lethal-guitar** [comment]
Superseded by #839
