### ISSUE TITLE
Optional enhancement : Explore in-game download option for shareware version of Duke Nukem II

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#415]
It is discussed in #412 . It would be really good for end user experience if the Rigel Engine can directly download shareware game files from a URI and load game resources from it without requiring non-tech savvy end user to do any complex operation.

Doom 3 webassembly already does it. It downloads its demo for resources. http://wasm.continuation-labs.com/d3demo/

**Comment by lethal-guitar** [comment]
I've created an issue #417 to cover some prerequisite refactoring work. Once that's done, I would imagine doing this roughly as follows:

* At the beginning of `gameMain()`, check if we have a valid `gamePath`. If so, continue with the regular startup sequence, as today.
* If there's no valid game path, instantiate a game mode which handles the download, and then continues once that's finished.

This new game mode would use ImGui to show a UI with a little message telling the user what's going on, and offering two buttons: "Download" and "Quit". If #413 is already done, we could have "Choose existing" instead of "Quit".

When the user presses "Download", we download the shareware archive from the 3D Realms website (or maybe there could be a list of known download URLs?), unzip it into the preferences directory, and set the game path accordingly.

The last used game path should then be stored in the user profile, so that the game picks up the downloaded data automatically when launched the next time.

# Required dependencies

We need something to make HTTP requests, and something to unzip archives. Curl and Zlib would be obvious candidates, but maybe some other libraries could make sense too.

If possible without too much hassle, it would be nice if those dependencies could be kept optional, so that RigelEngine can be built without the automatic download feature if desired.

**Comment by s-martin** [comment]
It should be evaluated, if the proposed in-game download could trigger anti-virus software, because downloading and unzipping could be recognized as suspicious behavior.

Another idea would be to provide an RigelEngine installer, which could download the shareware game files.
WiX could be a solution for Windows, for OSX there's already a ticket #401 open.

**Comment by lethal-guitar** [comment]
@s-martin thanks, that's a very good point! Now that I think about it, even if antivirus software doesn't get triggered, we would be introducing potential security concerns into the game by downloading files from the internet. That's another argument to go with the installer-based solution.

An advantage of the in-game solution is that it would work for all platforms.

Not sure yet, what's best - maybe good to think about a bit (and maybe do some testing with anti-virus software, as you suggest).

**Comment by lethal-guitar** [comment]
Added #418 and #419

**Comment by pratikone** [comment]
Indeed, anti-virus and security concerns are definitely looking over. The installer might be a good idea too though as pointed out, it would be needed to be made separately for every platform. For the downloading files in-game, many games already do it, we can check how they are avoiding these problems.

**Comment by lethal-guitar** [comment]
One of the motivations for this feature was the Webassembly port, right? Was just wondering if it would be quicker and easier to add some JavaScript code to the HTML page used for the Webassembly version, to implement the Shareware download there. So the page would first download the data and then start RigelEngine - would something like that be possible?
