### ISSUE TITLE
Make userprofile as human-readable json file

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#460]
Make userprofile file as user readable json file. It doesn't contain anything confidential. Having a human-readable non-serialized file will aid in debugging efforts as well as any user modifications. 

constexpr auto PREF_PATH_ORG_NAME = "lethal-guitar";
constexpr auto PREF_PATH_APP_NAME = "Rigel Engine";
constexpr auto USER_PROFILE_FILENAME = "UserProfile_v2.rigel";

Also, why not save the userprofile file local to executable ?

**Comment by lethal-guitar** [comment]
> Having a human-readable non-serialized file will aid in debugging efforts

Fully agreed, it would be quite handy for debugging and development.

The reason I decided to go with a binary format is that I wanted to avoid making it too easy to "cheat" and modify saved games/high scores. There is nothing stopping a determined user, of course, but having a little bit of a hurdle in the way felt better to me.

Of course, we could add a command-line option or something to optionally store the profile in textual form. What do you think?

> Also, why not save the userprofile file local to executable ?

It's generally best practice to store that kind of data in a user-specific location, to my knowledge. This keeps the game's installation immutable and separate from any mutable data. Most modern games handle this in a similar way, which is why SDL offers a `SDL_GetPrefPath` function, after all.

One reason why to do this is that the directory containing the binary might not be writeable by the user for security reasons. This is currently not the case for RigelEngine, since there is no installer, so the binary will be where ever the user put it. But in the future, once we have proper DEB packages for Linux and an app bundle for OS X, and maybe an installer for Windows, the binary might be in a non-writeable location. 

Another reason is that storing the profile in a user-specific directory makes it possible to have different profiles for different users on the same system, in case of a multi-user setup. Not sure how common that use case is nowadays.

**Comment by lethal-guitar** [comment]
Another option might be storing the saved games/high scores in a binary file, and using a separate, plain-text file for options 🤔

**Comment by lethal-guitar** [comment]
Ok, I've been thinking about this some more, and one way to get a plain-text profile file while still adding some effort for "cheating" would be to add a hash of the saved games and high scores part of the profile. That way, we can keep storing everything in one file, make it human readable, but any changes to the saved games or high scores could be detected if the hash doesn't match.

What do you think?

**Comment by lethal-guitar** [comment]
Thinking about it some more, I don't like the hash-based approach so much anymore. It's not clear what to do if the hash doesn't match - do we reject the profile and create a new one? It would be pretty nasty for the user to lose all their progress just because of that, so you'd want to keep a backup that you can revert to, or something.

Instead, we might as well keep two copies of the profile, a textual one, and a binary one. When the game starts, it checks which of the two is newer, and uses the options from that one. For the progress-related data (saved games and high scores), it checks that the binary and plain text versions are equal. If not, it uses the binary version and discards the plain text one. When writing the profile, the binary and plain text file are both written.

As far as I can tell, this is the best option so far:

* It allows modification of non-progress data via text file, and inspection of the progress data for debugging
* It makes "tampering" with the progress data more difficult, since users have to modify the binary file for that
* It keeps backwards compatibility with older versions of the game, which can only read binary profiles.

**Comment by pratikone** [comment]
We might be complicating this process by keeping 2 variants of the same file. I can do some search to see how other games DID it (example : Doom).

**Comment by lethal-guitar** [comment]
> user doing cheating locally shouldn't affect us

True, it doesn't affect _us_. I personally don't care if someone is cheating :smile:  But I'm not trying to protect the project, my aim is to protect people from themselves: If it's too easy to modify the save files/high score lists, someone might be tempted to do it, but then regret it later, as beating the game "honestly" may give a greater sense of accomplishment.

> Given the source is available, it would be trivial to just build a new version to "cheat"

It's not very hard, I agree. But it still requires more effort compared to editing a text file. Like when you need to get a save game editor for a game. It's totally possible and people will do it, but the extra bit of effort required could stop someone.

That was my thinking for choosing a binary format. But in the end, I don't know how much sense this makes to other people :thinking:

I'm not opposed to switching to plain text, but compatibility with older versions of RigelEngine is an issue, and the only way I can think of to avoid breaking backwards compatibility is to write the file in two formats. I already had to break compatibility once when going from 0.4.x to 0.5.0, and I'd prefer not to do it that often.

**Comment by pratikone** [comment]
I understand the backward compatibility part. My point is that a typical text file config/save system won't have backward incompatibility issues (if implemented with care), a serialized binary format will have. We can go with 2 variants but as long as a binary file is there, there will be cases of backward compat breaks in the future.

**Comment by lethal-guitar** [comment]
What I mean by backwards compatibility is the following:

Versions of RigelEngine up to 0.5.0 only know how to read the binary format. Let's say we change to plain text in version 0.6.

If I then use version 0.6 to play the game,  and make some progress, the profile will be stored as plain text. If I go back to version 0.5, it will not know about the plain text profile, and so I won't be able to have the same profile anymore.

If we keep the binary format, a profile saved by version 0.6 will still be readable by version 0.5. You could argue that this is not a common use case, why would you want to go back to an older version if there is a newer one? But I think this kind of compatibility is quite useful in the long run, for example if we discover a bug later on and want to bisect across different versions. That's why I'd like to avoid changing the user profile in any way that makes it unreadable by old versions.

> as long as a binary file is there, there will be cases of backward compat breaks in the future.

I'm not sure I understand. The current binary format is just a version of the JSON encoded using [msgpack](https://msgpack.org/). Regardless of how the JSON is encoded on disk, we can always break backwards compatibility, for example if we would rename the `saveSlots` entry to `savedGames`, old versions won't be able to load profiles from new versions, even if the file is stored as plain text?

In any case, I had another idea that might give us what we want in a much simpler way. I'll make a PR.
