### ISSUE TITLE
Game pad support: Access in-game menu via select button

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#487]
Currently, in-game menus can be partially navigated with the game pad, but there is no way to enter those menus without using the keyboard. It would be nice if the select button (small button to the right of the Xbox button on a Xbox controller) would bring up a menu, from which the various in-game menus like options, save and load could be accessed.

**Comment by pratikone** [comment]
additional work on this would be navigating menus using the sticks instead of just dpads. One can play the game using Left and right sticks or dpad but the menu only works with dpad.

**Comment by lethal-guitar** [comment]
Yeah, stick navigation would be nice as well!

**Comment by NeonLightning** [comment]
ya making some controller friendly controls would be useful. at present my whole controller consists of directions, and then jump and fire repeated on all other 12 buttons.

**Comment by lethal-guitar** [comment]
@NeonLightning what kind of controller are you using? I assume you'd like way to reconfigure/rebind the controller mappings, is that correct? I'll create a separate issue for that, then. Making the keyboard controls configurable is already planned, so it would make sense to implement controller remapping at the same time.

This issue is about better support for the in-game menus, which is currently in the works.

**Comment by NeonLightning** [comment]
i'm using an odroid go advance

**Comment by lethal-guitar** [comment]
@NeonLightning oh nice that looks cool, I didn't know about that device! So are you running RigelEngine on the Odroid? How well does it run?

**Comment by NeonLightning** [comment]
it ran just fine as far as i can tell. just makes it look like a franken-device with a keyboard hanging off it lol.
also the oga is great if you can get one in stock.

**Comment by lethal-guitar** [comment]
Nice! Yeah I'll definitely try and grab one.

There is already a branch for making the in-game menus available with a gamepad: #553 It just needs a bit of cleanup, but is already working. I don't know which of the Odroid's buttons would be considered "start" by SDL though, so not sure if it would work out of the box.

I'll focus on making the options menu controller friendly once that's merged.

**Comment by NeonLightning** [comment]
it should work out of the box and if not sdl should be able to follow an updated gamecontrollerdb.txt
`19000000010000000100000001010000,odroidgo2_joypad,platform:Linux,a:b0,b:b1,x:b3,y:b2,back:b10,start:b15,leftstick:b12,rightstick:b13,leftshoulder:b4,rightshoulder:b5,dpup:b6,dpdown:b7,dpleft:b8,dpright:b9,leftx:a0,lefty:a1,lefttrigger:b11,righttrigger:b14,
`

**Comment by NeonLightning** [comment]
i tried to run the new menu branch and i get a segfault on after the welcome on the command line

**Comment by lethal-guitar** [comment]
@NeonLightning huh, weird.. :thinking: Any chance you could get a stack trace by running in `gdb`? Ideally on a build with `cmake . -DCMAKE_BUILD_TYPE=Debug`.

On the weekend when I have more time, I'll add some logging to help with figuring out where it might be going wrong.

**Comment by NeonLightning** [comment]
i'm not really sure how to use gdb and the one i installed on the oga doesn't seem to have the stack function for some reason.

**Comment by lethal-guitar** [comment]
Normally, the following should do:

```
gdb ./src/RigelEngine

# In the gdb prompt:
> r
# Now the game runs until it hits the segfault. Once that happens, back at the gdb prompt:
> bt
```

Does the current `master` branch still run fine for you? Wondering if it's something on the gamepad menu branch that broke it, or some of the recent OpenGL changes..

**Comment by NeonLightning** [comment]
`[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
librga:RGA_GET_VERSION:4.00,4.000000 
ctx=0x5555b27eb0,ctx->rgaFd=3 
Rga built version:version:+2017-09-28 10:12:42 
================================================================================
                            Welcome to RIGEL ENGINE!

  A modern reimplementation of the game Duke Nukem II, originally released in
  1993 for MS-DOS by Apogee Software.

You need the original game's data files in order to play, e.g. the freely
available shareware version.

Rigel Engine Copyright (C) 2016, Nikolai Wuttke.
Rigel Engine comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under certain conditions.
For details, see https://www.gnu.org/licenses/gpl-2.0.html
================================================================================

rk-debug mali-ver=rsx-p0-1.2
[New Thread 0x7fb51591c0 (LWP 3825)]
[New Thread 0x7fb49581c0 (LWP 3826)]
[New Thread 0x7fb41571c0 (LWP 3827)]
[New Thread 0x7fb39561c0 (LWP 3828)]
[New Thread 0x7fb31551c0 (LWP 3829)]
[New Thread 0x7fb29541c0 (LWP 3830)]
[New Thread 0x7fb21531c0 (LWP 3831)]
[New Thread 0x7fb18561c0 (LWP 3832)]

Thread 1 "RigelEngine" received signal SIGSEGV, Segmentation fault.
0x0000007fb7ea2400 in ?? () from /usr/lib/libSDL2-2.0.so.0
(gdb) bt
#0  0x0000007fb7ea2400 in ?? () from /usr/lib/libSDL2-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
`
but i'll try and compile the latest git again.

**Comment by NeonLightning** [comment]
it segfaulted i'm trying with -DUSE_GL_ES now

**Comment by NeonLightning** [comment]
ya it's the opengl stuff the gamepad version works great. takes a while to start but once it does it plays fine. little bit more flicker to the display than the opengl one had although that might just be in my head.

**Comment by NeonLightning** [comment]
did notice that with RigelEngine i need to pass SDL_GAMECONTROLLERCONFIG_FILE="/path/gamecontrollerdb.txt" to have controls.

**Comment by lethal-guitar** [comment]
@NeonLightning I've created some follow-up issues to look into once my OGA arrives. I'll close this one in a moment, when merging the gamepad menu branch to master.

Regarding:
> takes a while to start

That could be due to building as debug (as I suggested earlier). If you rebuild with `-DCMAKE_BUILD_TYPE=Release`, it should be a bit quicker.
