### ISSUE TITLE
32-bit builds for windows

### ISSUE THREAD

**Issue by Mouradouchane** [lethal-guitar/RigelEngine#602]

**Comment by lethal-guitar** [comment]
Can do. Just to clarify, I assume you mean downloadable builds? Or just being able to build locally in 32-bit configuration?

**Comment by Mouradouchane** [comment]
I'm so beginner , when I'm trying to build this project on my win 32bit using cmake its give me errors  when i read documentation i saw no 32bit support just 64bit , so is there any way to build & run this project on win32 ?

**Comment by lethal-guitar** [comment]
What errors do you get? Can you paste them here?

It *is* possible to build on Windows 32-bit, but there are a few small changes necessary. I pushed a branch with those changes: [32-bit-win-builds](https://github.com/lethal-guitar/RigelEngine/tree/32-bit-win-builds). Give it a shot, and if you still get errors, feel free to paste them here and we can figure it out together.

The reason the documentation says that only 64-bit is supported is because I currently have no CI coverage for 32-bit builds, so even if I merge those fixes, it would be easy for me to reintroduce issues without noticing, as I only work on 64-bit myself. But with the fixes from my branch, I was able to successfully build and run in 32-bit mode.

**Comment by lethal-guitar** [comment]
@Mouradouchane I've updated the README on my branch with instructions for building 32-bit: https://github.com/lethal-guitar/RigelEngine/blob/b5deca65a9fb5bf24fd6f0a6c5df6056dda5d15c/README.md#windows-builds

Have a look, and let me know if these instructions work for you when using that branch.

**Comment by Mouradouchane** [comment]
I have followed the new instructions in the documentation, but I got this one
![image](https://user-images.githubusercontent.com/34870188/99896408-90221e80-2c90-11eb-9f96-49a8e5b7a5f6.png)

**Comment by lethal-guitar** [comment]
@Mouradouchane ah, I see. To fix that, you need to run `git submodule --init --recursive` once, and then rerun CMake. If there are still errors, try deleting all the files inside the `build` directory, and then rerunning CMake. Hope that helps, let me know if there are more errors.

Also see https://github.com/lethal-guitar/RigelEngine#get-the-sources.

**Comment by Mouradouchane** [comment]
yeah , generate full project successfully , but i get some errors in rigle_core 
i think that because i have old GPU with OpenGL v1.1.0 , and thank you for your time
![image](https://user-images.githubusercontent.com/34870188/99898922-ad151c80-2ca5-11eb-8ca1-b7173add2c57.png)

**Comment by lethal-guitar** [comment]
@Mouradouchane did you check out my branch (`git checkout 32-bit-win-builds`)? This is one of the errors I had to fix to get it to build in 32-bit.

**Comment by lethal-guitar** [comment]
What GPU do you have? It might still be possible to run the game on your computer by using GL ES.

**Comment by Mouradouchane** [comment]
GPU intle 64MB , i think every think it's ok maybe problem coming from my old GPU & OpenGL .
GL-ES running game on browser is that simple ?

**Comment by lethal-guitar** [comment]
There is an experimental Wasm build option for running Rigel in a browser, but it's actually possible to use OpenGL ES even on Desktop. Often, older graphics cards do not support OpenGL 3, but do support OpenGL ES if the driver supports it.

Unfortunately, I have no experience with this on Windows, only on Linux. But according to [this article](https://www.saschawillems.de/blog/2015/04/19/using-opengl-es-on-windows-desktops-via-egl/), it should be supported by Intel GPUs.

So you could try passing `-DUSE_GL_ES=ON` to CMake, and then rebuild.

In any case, the build error you posted is definitely not related to your graphics card. The code will always compile, because OpenGL is loaded at runtime, not build time. So if your GPU is really too old, this would cause an error when starting the game, not during compilation.

**Comment by Mouradouchane** [comment]
thanks you

**Comment by lethal-guitar** [comment]
@Mouradouchane sorry it didn't work for you, and thanks for creating the issue! I've merged the fixes and readme changes now, so if someone else wants to build for Windows 32-bit, they will have better instructions and hopefully no build errors. 🙂
