### ISSUE TITLE
Create Docker containers for easy ARM cross-compilation

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#623]
This would allow us to more easily build binaries for Raspberry Pi/Odroid Go

**Comment by bencsikandrei** [comment]
Hey, how about we start with a docker container for ubuntu:latest (20.04 as I write this)?

It would be useful to run tests locally without the need for g++-8 - used in CI.
They way I see it a script could be used for both the CI and this image's build steps (to reduce duplication and to ensure the 2 envs are the same). Why is this good? Well it would allow people to run tests and all before making a MR (at least on ubuntu - the rest is more complicated...)

Would this be interesting to you? I actually already have the dockerfile since I needed it to understand why some CI step failed.

**Comment by lethal-guitar** [comment]
> Hey, how about we start with a docker container for ubuntu:latest (20.04 as I write this)?

Sure why not, sounds like other people might find it useful too. And if you already have the Dockerfile, we might as well put it in the repo 🙂
