### ISSUE TITLE
E3L3 - X coords out of bounds

### ISSUE THREAD

**Issue by sub205** [lethal-guitar/RigelEngine#718]
Currently i progressed to E3L3 and in the first few seconds of the level the above error pops up and the game quits.
I can attach a savegame if somebody is telling me where it's stored.

EDIT: Seems to happen after walking to the right.

**Comment by lethal-guitar** [comment]
@sub205 thanks for reporting, and sorry about that! You're playing in wide-screen mode I assume?

This should already be fixed on the master branch, and so will be fixed in the upcoming 0.8.0 release. It's still going to take a bit of time before I'm ready to release it, but you can already grab a newer build here: https://ci.appveyor.com/api/buildjobs/2v8ght1u2l62b0aq/artifacts/rigelengine_win_x64.zip

That should fix the issue for you hopefully, let me know!

**Comment by lethal-guitar** [comment]
@sub205 did you have a chance to try with the latest release?

**Comment by sub205** [comment]
Yes, sorry for the late reply. Problem fixed!

**Comment by lethal-guitar** [comment]
@sub205 cool, no worries!
