### ISSUE TITLE
Final boss has wrong death animation

### ISSUE THREAD

**Issue by snoopin1** [lethal-guitar/RigelEngine#719]
In the original, the Episode Four boss explodes completely upon being defeated; it does not fly away like the other bosses.

**Comment by lethal-guitar** [comment]
This is an interesting one, the fly away does still happen in the original game's code, but the boss sprite is made invisible so it appears as if he explodes completely. However, for some reason the sprite already disappears even before the fly away part of the sequence, making it so that only the explosions are visible. To me, that seemed like a bug and so I decided to change that and keep the sprite visible.

However, it does make sense for the final boss to not fly away, story wise. So I would suggest the following:

I'll make the boss still visible during the explosions part, unlike the original, but I will remove the fly away part. What do you think?

**Comment by snoopin1** [comment]
I think that is a good idea.

I assumed the 4th boss disappearing when exploding was a deliberate choice as the story says Duke vanquished the Rigelatin leader, although I see how it's possible the sprite disappearing could just be an oversight.
