### ISSUE TITLE
Duke Nukem 1 Support?

### ISSUE THREAD

**Issue by MasterO2** [lethal-guitar/RigelEngine#760]
@lethal-guitar 

I'm not sure where exactly to ask, so I'll ask here:

Will you also make a source port for **Duke Nukem 1**?

**Comment by lethal-guitar** [comment]
Hi @MasterO2, I have no plans to work on a Duke 1 engine, since there is already one (made by someone else): [ReDuke](http://k1n9duk3.shikadi.net/reduke.html).

As for where to ask, I don't mind GitHub issues. We do also have a [Discord server](https://discord.gg/QKYB6u4Kew) though, which is a good place for any general questions.

**Comment by kartiksharmakk** [comment]
@lethal-guitar  https://lethalguitar.wordpress.com/2023/10/03/duke-nukem-12-remastered/  

>Reverse engineering Duke Nukem 1 was a lot of fun, and it was quite interesting to see the differences in architecture and coding style between the two games – the first one features a lot of copy & pasted code and basically no generalized systems at all.

So will rigel engine be updated now with duke 1 support after you reversed duke 1 ?
