### ISSUE TITLE
Make the smooth scrolling option affect non-flying enemy movement

### ISSUE THREAD

**Issue by Calinou** [lethal-guitar/RigelEngine#835]
Related to https://github.com/lethal-guitar/RigelEngine/issues/834.

The smooth movement option currently doesn't affect non-flying enemy movement such as these ones:

![image](https://user-images.githubusercontent.com/180032/158906157-c4691c30-a554-427a-b581-35233e5d5528.png)

Smooth movement appears to work for flying enemies though.

**Comment by lethal-guitar** [comment]
@Calinou thanks for the report! It's actually not so easy with these enemies, since they don't move 1 tile each frame, but rather 1 tile every other frame. So you could say that they move by 0.5 tiles every frame, but the game logic isn't implemented like that (there is no concept of fractional tile positions). 

We could enable smoothing for these, but it's not going to look as good as it does for objects that move faster. Since you get a kind of "stop & go" effect. So I decided to not enable smoothing for any "walking" enemies for now, and maybe revisit it later.

If you'd like to see for yourself how the blue guard enemy looks with smoothing, you can add a call to `engine::enableInterpolation(entity);` to the configuration [here](https://github.com/lethal-guitar/RigelEngine/blob/71161705a15122d729b527df71ac1120df6f57a8/src/game_logic/entity_configuration.ipp#L1534).

Some non-flying enemies do have smoothing btw, for example the cylindrical robot that teleports in. For that one it works because it also moves at 1 tile/frame.
