### ISSUE TITLE
Widescreen HUD?

### ISSUE THREAD

**Issue by OpenRift412** [lethal-guitar/RigelEngine#843]
Something that always seemed out of place about playing in widescreen is how there's a large chunk of the space on the bottom-left side where the HUD just stops. The idea with the original HUD was that it was a picture-in-picture situation, as I'm sure you know, while this effect is currently broken in the Rigel Engine. Are there any plans on extending the existing HUD so that it better fits the wider ratio and the intended look?

**Comment by lethal-guitar** [comment]
Yeah I've been thinking about this quite a bit. Truly extending the HUD is a bit tricky because it would involve making new artwork. I'm sure it's also possible to make something new out of the existing textures (i.e. combining different parts in new ways) but it probably doesn't look as good as something tailor-made. I'm no good at pixel art (or any art, really 😄) so this would be something where I need help from someone more skilled at that.

There are some other possibilities though. What I've been experimenting with is this:

![RigelEngine_2022-03-25_150821](https://user-images.githubusercontent.com/1821027/161840591-3fcc8a43-0e15-4e71-ac8e-ab374ffe2cab.png)

So the right-hand side of the HUD is gone and the relevant information is shown via overlays instead, with only the bottom part remaining. I believe this improves the widescreen mode already because:

1. The HUD can now always be centered, especially useful in ultrawide
2. More of the horizontal screen real estate can be used.

You could imagine taking this even further, and turning the remaining HUD information (score, weapon, ammo, letters) into smaller overlays as well, or maybe show all of that in a smaller format inside a small black strip at the bottom of the screen, similar to Crystal Caves/Secret Agent. So basically move away completely from the classic HUD, and replace it with a more minimal version. I would still offer the classic HUD as an option of course.

One other possibility would be to simply make the bottom-left part of the classic HUD stretch out longer to cover the entire width of the screen, basically making the section with the score display wider. That would not require any new art, and retain the original design intent somewhat, but I think it might look pretty ridiculous once you get into ultrawide territory.

Let me know what you think!

**Comment by OpenRift412** [comment]
> One other possibility would be to simply make the bottom-left part of the classic HUD stretch out longer to cover the entire width of the screen, basically making the section with the score display wider. That would not require any new art, and retain the original design intent somewhat, but I think it might look pretty ridiculous once you get into ultrawide territory.
> 
> Let me know what you think!

I think this would probably be the best strategy for this. It would look ridiculous in ultrawide, but so do most retro games, really. I'd say that for ultrawide you could include the status bar/overlay approach as an option to accommodate, then have some tiling textures fill the black spaces on the black corners.

Is the HUD graphic all one sprite? If so, could you send it to me? I haven't had any luck finding it in the resource files.

**Comment by lethal-guitar** [comment]
> Is the HUD graphic all one sprite? If so, could you send it to me? I haven't had any luck finding it in the resource files.

It's three separate sprites, stored as frames of actor number 77. Any tool that can extract graphics from `ACTORS.MNI` should be able to extract it. I'll post it here tomorrow!

**Comment by OpenRift412** [comment]
> > Is the HUD graphic all one sprite? If so, could you send it to me? I haven't had any luck finding it in the resource files.
> 
> It's three separate sprites, stored as frames of actor number 77. Any tool that can extract graphics from `ACTORS.MNI` should be able to extract it. I'll post it here tomorrow!

Alright, thanks. Also, here's a little proof of concept I whipped up in Photoshop.
![Rigel wideHUD](https://user-images.githubusercontent.com/29780788/161860798-4627f7dc-8e7c-4689-85a8-e3ef747f0e08.png)

**Comment by lethal-guitar** [comment]
Nice, that looks good! 👍🏻 Good idea to keep the part with the two blue arrows in its original position. In my head, I saw that part moved to the far left but I think your version looks better.

Here are the sprites:

![actor77_frame2](https://user-images.githubusercontent.com/1821027/161924072-bb21528e-10ed-4048-a653-b1175aac4a5d.png)
![actor77_frame0](https://user-images.githubusercontent.com/1821027/161924069-b0f541a0-2916-47b0-a7e1-bd618ef28404.png)
![actor77_frame1](https://user-images.githubusercontent.com/1821027/161924071-4bd106a3-e295-46aa-b544-b864085e4d99.png)

**Comment by lethal-guitar** [comment]
I've implemented a prototype of your mockup:
[RigelEngine_extended_hud_wip.zip](https://github.com/lethal-guitar/RigelEngine/files/8425767/RigelEngine_extended_hud_wip.zip)

**Comment by OpenRift412** [comment]
> I've implemented a prototype of your mockup: [RigelEngine_extended_hud_wip.zip](https://github.com/lethal-guitar/RigelEngine/files/8425767/RigelEngine_extended_hud_wip.zip)
> 
> Just one little tweak, I removed the gray part on the far left side. Let me know what you think!

Looks really good! Definitely a lot more fitting for widescreen ;)

**Comment by lethal-guitar** [comment]
> Looks really good! Definitely a lot more fitting for widescreen ;)

Cool, I'll try to merge this pretty soon then. Thanks for testing.

**Comment by lethal-guitar** [comment]
> Oh and by the way, here's a graphic for the ultrawide HUD, in case you're still interested in implementing that! Should fit in both 16:9 and 21:9.

Awesome, thank you, that's great! I'll definitely make use of that. I won't work much more on the HUD for now, as there are some other things I'd like to get out of the way first, but I'll get back to it after that!

**Comment by lethal-guitar** [comment]
@OpenRift412 I've implemented your ultra-wide HUD as well as the bottom part + floating overlays variant. You can now choose between HUD styles in the options menu.

Let me know what you think 🙂And thanks again for making that ultra-wide HUD graphic!
[RigelEngine_hud_styles.zip](https://github.com/lethal-guitar/RigelEngine/files/8686227/RigelEngine_hud_styles.zip)

**Comment by OpenRift412** [comment]
> @OpenRift412 I've implemented your ultra-wide HUD as well as the bottom part + floating overlays variant. You can now choose between HUD styles in the options menu.
> 
> Let me know what you think 🙂And thanks again for making that ultra-wide HUD graphic! [RigelEngine_hud_styles.zip](https://github.com/lethal-guitar/RigelEngine/files/8686227/RigelEngine_hud_styles.zip)

Looks great! Thanks for the chance to implement my design!
