### ISSUE TITLE
Game Data Directory Issues

### ISSUE THREAD

**Issue by AskaLangly** [lethal-guitar/RigelEngine#910]
So, I've moved my game data files to a folder within the folder Rigel is in; a folder called `game`.
The directory Rigel is located is `E:\Other Games\Duke Nukem 2`.

Rigel is unable to find the game data, which is normal, but it does not invoke a directory picker, as I've already used Rigel at least once.
So, I've tried opening Rigel in Command Prompt, pointing at the directory the game is in.
Rigel still tells me that it can't find `NUKEM2.CMP`.

I've tried the following commands:
`RigelEngine "E:\Other Games\Duke Nukem 2\game"` and `RigelEngine "./game"`

*Note the second one, as I want a fully portable install with game data always pointing at the `game` directory from within.*
***Maybe I'm complicating things a bit...***

Could you please add `"gamePath":` in `options.txt`, instead of inside the user profile?

**Comment by lethal-guitar** [comment]
@AskaLangly I'm guessing you're using the newly introduced portable mode? The way it's currently implemented, a game path specified on the command line will be ignored when `portable.txt` is detected. In other words, if you want to use the portable mode, the game data files _have_ to be in the same directory as `RigelEngine.exe`. 

I can certainly move the stored game path into the options file, but due to what I just mentioned, it wouldn't help in your case - whatever is stored in the user profile (or options file, if I were to change it) is also  ignored.

**Comment by lethal-guitar** [comment]
One thing I could do, is to change the error message so that it clearly indicates whether portable mode is active, and where it would expect to find the files?

**Comment by lethal-guitar** [comment]
@AskaLangly I'm going to close this, see my messages above for context.
